// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/message"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/workspace"
)

// ConversationCreate is the builder for creating a Conversation entity.
type ConversationCreate struct {
	config
	mutation *ConversationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConversationCreate) SetCreatedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableCreatedAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConversationCreate) SetUpdatedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableUpdatedAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ConversationCreate) SetDeletedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableDeletedAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ConversationCreate) SetUserID(v int64) *ConversationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *ConversationCreate) SetWorkspaceID(v int64) *ConversationCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableWorkspaceID(v *int64) *ConversationCreate {
	if v != nil {
		_c.SetWorkspaceID(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *ConversationCreate) SetTitle(v string) *ConversationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableTitle(v *string) *ConversationCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetKnowledgeIds sets the "knowledge_ids" field.
func (_c *ConversationCreate) SetKnowledgeIds(v []int64) *ConversationCreate {
	_c.mutation.SetKnowledgeIds(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ConversationCreate) SetMetadata(v map[string]interface{}) *ConversationCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ConversationCreate) SetUser(v *User) *ConversationCreate {
	return _c.SetUserID(v.ID)
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_c *ConversationCreate) SetWorkspace(v *Workspace) *ConversationCreate {
	return _c.SetWorkspaceID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_c *ConversationCreate) AddMessageIDs(ids ...int64) *ConversationCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the Message entity.
func (_c *ConversationCreate) AddMessages(v ...*Message) *ConversationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the ConversationMutation object of the builder.
func (_c *ConversationCreate) Mutation() *ConversationMutation {
	return _c.mutation
}

// Save creates the Conversation in the database.
func (_c *ConversationCreate) Save(ctx context.Context) (*Conversation, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConversationCreate) SaveX(ctx context.Context) *Conversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConversationCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if conversation.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized conversation.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := conversation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if conversation.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized conversation.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := conversation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := conversation.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConversationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Conversation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Conversation.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Conversation.user_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Conversation.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := conversation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Conversation.title": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Conversation.user"`)}
	}
	return nil
}

func (_c *ConversationCreate) sqlSave(ctx context.Context) (*Conversation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConversationCreate) createSpec() (*Conversation, *sqlgraph.CreateSpec) {
	var (
		_node = &Conversation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(conversation.Table, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(conversation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(conversation.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(conversation.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.KnowledgeIds(); ok {
		_spec.SetField(conversation.FieldKnowledgeIds, field.TypeJSON, value)
		_node.KnowledgeIds = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(conversation.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.UserTable,
			Columns: []string{conversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.WorkspaceTable,
			Columns: []string{conversation.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Conversation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ConversationCreate) OnConflict(opts ...sql.ConflictOption) *ConversationUpsertOne {
	_c.conflict = opts
	return &ConversationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Conversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConversationCreate) OnConflictColumns(columns ...string) *ConversationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConversationUpsertOne{
		create: _c,
	}
}

type (
	// ConversationUpsertOne is the builder for "upsert"-ing
	//  one Conversation node.
	ConversationUpsertOne struct {
		create *ConversationCreate
	}

	// ConversationUpsert is the "OnConflict" setter.
	ConversationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ConversationUpsert) SetUpdatedAt(v time.Time) *ConversationUpsert {
	u.Set(conversation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateUpdatedAt() *ConversationUpsert {
	u.SetExcluded(conversation.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ConversationUpsert) SetDeletedAt(v time.Time) *ConversationUpsert {
	u.Set(conversation.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateDeletedAt() *ConversationUpsert {
	u.SetExcluded(conversation.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ConversationUpsert) ClearDeletedAt() *ConversationUpsert {
	u.SetNull(conversation.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ConversationUpsert) SetUserID(v int64) *ConversationUpsert {
	u.Set(conversation.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateUserID() *ConversationUpsert {
	u.SetExcluded(conversation.FieldUserID)
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *ConversationUpsert) SetWorkspaceID(v int64) *ConversationUpsert {
	u.Set(conversation.FieldWorkspaceID, v)
	return u
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateWorkspaceID() *ConversationUpsert {
	u.SetExcluded(conversation.FieldWorkspaceID)
	return u
}

// ClearWorkspaceID clears the value of the "workspace_id" field.
func (u *ConversationUpsert) ClearWorkspaceID() *ConversationUpsert {
	u.SetNull(conversation.FieldWorkspaceID)
	return u
}

// SetTitle sets the "title" field.
func (u *ConversationUpsert) SetTitle(v string) *ConversationUpsert {
	u.Set(conversation.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateTitle() *ConversationUpsert {
	u.SetExcluded(conversation.FieldTitle)
	return u
}

// SetKnowledgeIds sets the "knowledge_ids" field.
func (u *ConversationUpsert) SetKnowledgeIds(v []int64) *ConversationUpsert {
	u.Set(conversation.FieldKnowledgeIds, v)
	return u
}

// UpdateKnowledgeIds sets the "knowledge_ids" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateKnowledgeIds() *ConversationUpsert {
	u.SetExcluded(conversation.FieldKnowledgeIds)
	return u
}

// ClearKnowledgeIds clears the value of the "knowledge_ids" field.
func (u *ConversationUpsert) ClearKnowledgeIds() *ConversationUpsert {
	u.SetNull(conversation.FieldKnowledgeIds)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *ConversationUpsert) SetMetadata(v map[string]interface{}) *ConversationUpsert {
	u.Set(conversation.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ConversationUpsert) UpdateMetadata() *ConversationUpsert {
	u.SetExcluded(conversation.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ConversationUpsert) ClearMetadata() *ConversationUpsert {
	u.SetNull(conversation.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Conversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConversationUpsertOne) UpdateNewValues() *ConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(conversation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Conversation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ConversationUpsertOne) Ignore() *ConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConversationUpsertOne) DoNothing() *ConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConversationCreate.OnConflict
// documentation for more info.
func (u *ConversationUpsertOne) Update(set func(*ConversationUpsert)) *ConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ConversationUpsertOne) SetUpdatedAt(v time.Time) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateUpdatedAt() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ConversationUpsertOne) SetDeletedAt(v time.Time) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateDeletedAt() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ConversationUpsertOne) ClearDeletedAt() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ConversationUpsertOne) SetUserID(v int64) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateUserID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *ConversationUpsertOne) SetWorkspaceID(v int64) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateWorkspaceID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateWorkspaceID()
	})
}

// ClearWorkspaceID clears the value of the "workspace_id" field.
func (u *ConversationUpsertOne) ClearWorkspaceID() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearWorkspaceID()
	})
}

// SetTitle sets the "title" field.
func (u *ConversationUpsertOne) SetTitle(v string) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateTitle() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateTitle()
	})
}

// SetKnowledgeIds sets the "knowledge_ids" field.
func (u *ConversationUpsertOne) SetKnowledgeIds(v []int64) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetKnowledgeIds(v)
	})
}

// UpdateKnowledgeIds sets the "knowledge_ids" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateKnowledgeIds() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateKnowledgeIds()
	})
}

// ClearKnowledgeIds clears the value of the "knowledge_ids" field.
func (u *ConversationUpsertOne) ClearKnowledgeIds() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearKnowledgeIds()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ConversationUpsertOne) SetMetadata(v map[string]interface{}) *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ConversationUpsertOne) UpdateMetadata() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ConversationUpsertOne) ClearMetadata() *ConversationUpsertOne {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *ConversationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConversationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConversationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ConversationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ConversationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ConversationCreateBulk is the builder for creating many Conversation entities in bulk.
type ConversationCreateBulk struct {
	config
	err      error
	builders []*ConversationCreate
	conflict []sql.ConflictOption
}

// Save creates the Conversation entities in the database.
func (_c *ConversationCreateBulk) Save(ctx context.Context) ([]*Conversation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Conversation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConversationCreateBulk) SaveX(ctx context.Context) []*Conversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Conversation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ConversationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ConversationUpsertBulk {
	_c.conflict = opts
	return &ConversationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Conversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ConversationCreateBulk) OnConflictColumns(columns ...string) *ConversationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ConversationUpsertBulk{
		create: _c,
	}
}

// ConversationUpsertBulk is the builder for "upsert"-ing
// a bulk of Conversation nodes.
type ConversationUpsertBulk struct {
	create *ConversationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Conversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ConversationUpsertBulk) UpdateNewValues() *ConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(conversation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Conversation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ConversationUpsertBulk) Ignore() *ConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ConversationUpsertBulk) DoNothing() *ConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ConversationCreateBulk.OnConflict
// documentation for more info.
func (u *ConversationUpsertBulk) Update(set func(*ConversationUpsert)) *ConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ConversationUpsertBulk) SetUpdatedAt(v time.Time) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateUpdatedAt() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ConversationUpsertBulk) SetDeletedAt(v time.Time) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateDeletedAt() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ConversationUpsertBulk) ClearDeletedAt() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ConversationUpsertBulk) SetUserID(v int64) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateUserID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *ConversationUpsertBulk) SetWorkspaceID(v int64) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateWorkspaceID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateWorkspaceID()
	})
}

// ClearWorkspaceID clears the value of the "workspace_id" field.
func (u *ConversationUpsertBulk) ClearWorkspaceID() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearWorkspaceID()
	})
}

// SetTitle sets the "title" field.
func (u *ConversationUpsertBulk) SetTitle(v string) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateTitle() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateTitle()
	})
}

// SetKnowledgeIds sets the "knowledge_ids" field.
func (u *ConversationUpsertBulk) SetKnowledgeIds(v []int64) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetKnowledgeIds(v)
	})
}

// UpdateKnowledgeIds sets the "knowledge_ids" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateKnowledgeIds() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateKnowledgeIds()
	})
}

// ClearKnowledgeIds clears the value of the "knowledge_ids" field.
func (u *ConversationUpsertBulk) ClearKnowledgeIds() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearKnowledgeIds()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ConversationUpsertBulk) SetMetadata(v map[string]interface{}) *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ConversationUpsertBulk) UpdateMetadata() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ConversationUpsertBulk) ClearMetadata() *ConversationUpsertBulk {
	return u.Update(func(s *ConversationUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *ConversationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ConversationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ConversationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ConversationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
