// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/knowledgefile"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/workspace"
)

// KnowledgeFileUpdate is the builder for updating KnowledgeFile entities.
type KnowledgeFileUpdate struct {
	config
	hooks    []Hook
	mutation *KnowledgeFileMutation
}

// Where appends a list predicates to the KnowledgeFileUpdate builder.
func (_u *KnowledgeFileUpdate) Where(ps ...predicate.KnowledgeFile) *KnowledgeFileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KnowledgeFileUpdate) SetUpdatedAt(v time.Time) *KnowledgeFileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *KnowledgeFileUpdate) SetDeletedAt(v time.Time) *KnowledgeFileUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableDeletedAt(v *time.Time) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *KnowledgeFileUpdate) ClearDeletedAt() *KnowledgeFileUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *KnowledgeFileUpdate) SetUserID(v int64) *KnowledgeFileUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableUserID(v *int64) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *KnowledgeFileUpdate) SetWorkspaceID(v int64) *KnowledgeFileUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableWorkspaceID(v *int64) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// ClearWorkspaceID clears the value of the "workspace_id" field.
func (_u *KnowledgeFileUpdate) ClearWorkspaceID() *KnowledgeFileUpdate {
	_u.mutation.ClearWorkspaceID()
	return _u
}

// SetFilename sets the "filename" field.
func (_u *KnowledgeFileUpdate) SetFilename(v string) *KnowledgeFileUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableFilename(v *string) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetFileType sets the "file_type" field.
func (_u *KnowledgeFileUpdate) SetFileType(v string) *KnowledgeFileUpdate {
	_u.mutation.SetFileType(v)
	return _u
}

// SetNillableFileType sets the "file_type" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableFileType(v *string) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetFileType(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *KnowledgeFileUpdate) SetFileSize(v int64) *KnowledgeFileUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableFileSize(v *int64) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *KnowledgeFileUpdate) AddFileSize(v int64) *KnowledgeFileUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *KnowledgeFileUpdate) SetStoragePath(v string) *KnowledgeFileUpdate {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableStoragePath(v *string) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *KnowledgeFileUpdate) SetContent(v string) *KnowledgeFileUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableContent(v *string) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *KnowledgeFileUpdate) ClearContent() *KnowledgeFileUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *KnowledgeFileUpdate) SetContentHash(v string) *KnowledgeFileUpdate {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableContentHash(v *string) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// ClearContentHash clears the value of the "content_hash" field.
func (_u *KnowledgeFileUpdate) ClearContentHash() *KnowledgeFileUpdate {
	_u.mutation.ClearContentHash()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *KnowledgeFileUpdate) SetMetadata(v map[string]interface{}) *KnowledgeFileUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *KnowledgeFileUpdate) ClearMetadata() *KnowledgeFileUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetStatus sets the "status" field.
func (_u *KnowledgeFileUpdate) SetStatus(v string) *KnowledgeFileUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *KnowledgeFileUpdate) SetNillableStatus(v *string) *KnowledgeFileUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *KnowledgeFileUpdate) SetUser(v *User) *KnowledgeFileUpdate {
	return _u.SetUserID(v.ID)
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *KnowledgeFileUpdate) SetWorkspace(v *Workspace) *KnowledgeFileUpdate {
	return _u.SetWorkspaceID(v.ID)
}

// Mutation returns the KnowledgeFileMutation object of the builder.
func (_u *KnowledgeFileUpdate) Mutation() *KnowledgeFileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *KnowledgeFileUpdate) ClearUser() *KnowledgeFileUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *KnowledgeFileUpdate) ClearWorkspace() *KnowledgeFileUpdate {
	_u.mutation.ClearWorkspace()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *KnowledgeFileUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeFileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *KnowledgeFileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeFileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KnowledgeFileUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if knowledgefile.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized knowledgefile.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := knowledgefile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeFileUpdate) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := knowledgefile.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileType(); ok {
		if err := knowledgefile.FileTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_type", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.file_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StoragePath(); ok {
		if err := knowledgefile.StoragePathValidator(v); err != nil {
			return &ValidationError{Name: "storage_path", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.storage_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := knowledgefile.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.content_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := knowledgefile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "KnowledgeFile.user"`)
	}
	return nil
}

func (_u *KnowledgeFileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgefile.Table, knowledgefile.Columns, sqlgraph.NewFieldSpec(knowledgefile.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgefile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(knowledgefile.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(knowledgefile.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(knowledgefile.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileType(); ok {
		_spec.SetField(knowledgefile.FieldFileType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(knowledgefile.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(knowledgefile.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(knowledgefile.FieldStoragePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(knowledgefile.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(knowledgefile.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(knowledgefile.FieldContentHash, field.TypeString, value)
	}
	if _u.mutation.ContentHashCleared() {
		_spec.ClearField(knowledgefile.FieldContentHash, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(knowledgefile.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(knowledgefile.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(knowledgefile.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefile.UserTable,
			Columns: []string{knowledgefile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefile.UserTable,
			Columns: []string{knowledgefile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefile.WorkspaceTable,
			Columns: []string{knowledgefile.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefile.WorkspaceTable,
			Columns: []string{knowledgefile.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgefile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// KnowledgeFileUpdateOne is the builder for updating a single KnowledgeFile entity.
type KnowledgeFileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *KnowledgeFileMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *KnowledgeFileUpdateOne) SetUpdatedAt(v time.Time) *KnowledgeFileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *KnowledgeFileUpdateOne) SetDeletedAt(v time.Time) *KnowledgeFileUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableDeletedAt(v *time.Time) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *KnowledgeFileUpdateOne) ClearDeletedAt() *KnowledgeFileUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *KnowledgeFileUpdateOne) SetUserID(v int64) *KnowledgeFileUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableUserID(v *int64) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *KnowledgeFileUpdateOne) SetWorkspaceID(v int64) *KnowledgeFileUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableWorkspaceID(v *int64) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// ClearWorkspaceID clears the value of the "workspace_id" field.
func (_u *KnowledgeFileUpdateOne) ClearWorkspaceID() *KnowledgeFileUpdateOne {
	_u.mutation.ClearWorkspaceID()
	return _u
}

// SetFilename sets the "filename" field.
func (_u *KnowledgeFileUpdateOne) SetFilename(v string) *KnowledgeFileUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableFilename(v *string) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetFileType sets the "file_type" field.
func (_u *KnowledgeFileUpdateOne) SetFileType(v string) *KnowledgeFileUpdateOne {
	_u.mutation.SetFileType(v)
	return _u
}

// SetNillableFileType sets the "file_type" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableFileType(v *string) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetFileType(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *KnowledgeFileUpdateOne) SetFileSize(v int64) *KnowledgeFileUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableFileSize(v *int64) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *KnowledgeFileUpdateOne) AddFileSize(v int64) *KnowledgeFileUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetStoragePath sets the "storage_path" field.
func (_u *KnowledgeFileUpdateOne) SetStoragePath(v string) *KnowledgeFileUpdateOne {
	_u.mutation.SetStoragePath(v)
	return _u
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableStoragePath(v *string) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetStoragePath(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *KnowledgeFileUpdateOne) SetContent(v string) *KnowledgeFileUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableContent(v *string) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *KnowledgeFileUpdateOne) ClearContent() *KnowledgeFileUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *KnowledgeFileUpdateOne) SetContentHash(v string) *KnowledgeFileUpdateOne {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableContentHash(v *string) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// ClearContentHash clears the value of the "content_hash" field.
func (_u *KnowledgeFileUpdateOne) ClearContentHash() *KnowledgeFileUpdateOne {
	_u.mutation.ClearContentHash()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *KnowledgeFileUpdateOne) SetMetadata(v map[string]interface{}) *KnowledgeFileUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *KnowledgeFileUpdateOne) ClearMetadata() *KnowledgeFileUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetStatus sets the "status" field.
func (_u *KnowledgeFileUpdateOne) SetStatus(v string) *KnowledgeFileUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *KnowledgeFileUpdateOne) SetNillableStatus(v *string) *KnowledgeFileUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *KnowledgeFileUpdateOne) SetUser(v *User) *KnowledgeFileUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *KnowledgeFileUpdateOne) SetWorkspace(v *Workspace) *KnowledgeFileUpdateOne {
	return _u.SetWorkspaceID(v.ID)
}

// Mutation returns the KnowledgeFileMutation object of the builder.
func (_u *KnowledgeFileUpdateOne) Mutation() *KnowledgeFileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *KnowledgeFileUpdateOne) ClearUser() *KnowledgeFileUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *KnowledgeFileUpdateOne) ClearWorkspace() *KnowledgeFileUpdateOne {
	_u.mutation.ClearWorkspace()
	return _u
}

// Where appends a list predicates to the KnowledgeFileUpdate builder.
func (_u *KnowledgeFileUpdateOne) Where(ps ...predicate.KnowledgeFile) *KnowledgeFileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *KnowledgeFileUpdateOne) Select(field string, fields ...string) *KnowledgeFileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated KnowledgeFile entity.
func (_u *KnowledgeFileUpdateOne) Save(ctx context.Context) (*KnowledgeFile, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *KnowledgeFileUpdateOne) SaveX(ctx context.Context) *KnowledgeFile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *KnowledgeFileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *KnowledgeFileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *KnowledgeFileUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if knowledgefile.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized knowledgefile.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := knowledgefile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *KnowledgeFileUpdateOne) check() error {
	if v, ok := _u.mutation.Filename(); ok {
		if err := knowledgefile.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.filename": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileType(); ok {
		if err := knowledgefile.FileTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_type", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.file_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StoragePath(); ok {
		if err := knowledgefile.StoragePathValidator(v); err != nil {
			return &ValidationError{Name: "storage_path", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.storage_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := knowledgefile.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.content_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := knowledgefile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "KnowledgeFile.user"`)
	}
	return nil
}

func (_u *KnowledgeFileUpdateOne) sqlSave(ctx context.Context) (_node *KnowledgeFile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(knowledgefile.Table, knowledgefile.Columns, sqlgraph.NewFieldSpec(knowledgefile.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "KnowledgeFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, knowledgefile.FieldID)
		for _, f := range fields {
			if !knowledgefile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != knowledgefile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgefile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(knowledgefile.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(knowledgefile.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(knowledgefile.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileType(); ok {
		_spec.SetField(knowledgefile.FieldFileType, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(knowledgefile.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(knowledgefile.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StoragePath(); ok {
		_spec.SetField(knowledgefile.FieldStoragePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(knowledgefile.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(knowledgefile.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(knowledgefile.FieldContentHash, field.TypeString, value)
	}
	if _u.mutation.ContentHashCleared() {
		_spec.ClearField(knowledgefile.FieldContentHash, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(knowledgefile.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(knowledgefile.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(knowledgefile.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefile.UserTable,
			Columns: []string{knowledgefile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefile.UserTable,
			Columns: []string{knowledgefile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefile.WorkspaceTable,
			Columns: []string{knowledgefile.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefile.WorkspaceTable,
			Columns: []string{knowledgefile.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &KnowledgeFile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{knowledgefile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
