// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/knowledgefile"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/workspace"
)

// KnowledgeFileCreate is the builder for creating a KnowledgeFile entity.
type KnowledgeFileCreate struct {
	config
	mutation *KnowledgeFileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *KnowledgeFileCreate) SetCreatedAt(v time.Time) *KnowledgeFileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *KnowledgeFileCreate) SetNillableCreatedAt(v *time.Time) *KnowledgeFileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *KnowledgeFileCreate) SetUpdatedAt(v time.Time) *KnowledgeFileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *KnowledgeFileCreate) SetNillableUpdatedAt(v *time.Time) *KnowledgeFileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *KnowledgeFileCreate) SetDeletedAt(v time.Time) *KnowledgeFileCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *KnowledgeFileCreate) SetNillableDeletedAt(v *time.Time) *KnowledgeFileCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *KnowledgeFileCreate) SetUserID(v int64) *KnowledgeFileCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetWorkspaceID sets the "workspace_id" field.
func (_c *KnowledgeFileCreate) SetWorkspaceID(v int64) *KnowledgeFileCreate {
	_c.mutation.SetWorkspaceID(v)
	return _c
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_c *KnowledgeFileCreate) SetNillableWorkspaceID(v *int64) *KnowledgeFileCreate {
	if v != nil {
		_c.SetWorkspaceID(*v)
	}
	return _c
}

// SetFilename sets the "filename" field.
func (_c *KnowledgeFileCreate) SetFilename(v string) *KnowledgeFileCreate {
	_c.mutation.SetFilename(v)
	return _c
}

// SetFileType sets the "file_type" field.
func (_c *KnowledgeFileCreate) SetFileType(v string) *KnowledgeFileCreate {
	_c.mutation.SetFileType(v)
	return _c
}

// SetFileSize sets the "file_size" field.
func (_c *KnowledgeFileCreate) SetFileSize(v int64) *KnowledgeFileCreate {
	_c.mutation.SetFileSize(v)
	return _c
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_c *KnowledgeFileCreate) SetNillableFileSize(v *int64) *KnowledgeFileCreate {
	if v != nil {
		_c.SetFileSize(*v)
	}
	return _c
}

// SetStoragePath sets the "storage_path" field.
func (_c *KnowledgeFileCreate) SetStoragePath(v string) *KnowledgeFileCreate {
	_c.mutation.SetStoragePath(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *KnowledgeFileCreate) SetContent(v string) *KnowledgeFileCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *KnowledgeFileCreate) SetNillableContent(v *string) *KnowledgeFileCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetContentHash sets the "content_hash" field.
func (_c *KnowledgeFileCreate) SetContentHash(v string) *KnowledgeFileCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_c *KnowledgeFileCreate) SetNillableContentHash(v *string) *KnowledgeFileCreate {
	if v != nil {
		_c.SetContentHash(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *KnowledgeFileCreate) SetMetadata(v map[string]interface{}) *KnowledgeFileCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *KnowledgeFileCreate) SetStatus(v string) *KnowledgeFileCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *KnowledgeFileCreate) SetNillableStatus(v *string) *KnowledgeFileCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *KnowledgeFileCreate) SetUser(v *User) *KnowledgeFileCreate {
	return _c.SetUserID(v.ID)
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_c *KnowledgeFileCreate) SetWorkspace(v *Workspace) *KnowledgeFileCreate {
	return _c.SetWorkspaceID(v.ID)
}

// Mutation returns the KnowledgeFileMutation object of the builder.
func (_c *KnowledgeFileCreate) Mutation() *KnowledgeFileMutation {
	return _c.mutation
}

// Save creates the KnowledgeFile in the database.
func (_c *KnowledgeFileCreate) Save(ctx context.Context) (*KnowledgeFile, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *KnowledgeFileCreate) SaveX(ctx context.Context) *KnowledgeFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KnowledgeFileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KnowledgeFileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *KnowledgeFileCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if knowledgefile.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized knowledgefile.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := knowledgefile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if knowledgefile.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized knowledgefile.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := knowledgefile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		v := knowledgefile.DefaultFileSize
		_c.mutation.SetFileSize(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := knowledgefile.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *KnowledgeFileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "KnowledgeFile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "KnowledgeFile.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "KnowledgeFile.user_id"`)}
	}
	if _, ok := _c.mutation.Filename(); !ok {
		return &ValidationError{Name: "filename", err: errors.New(`ent: missing required field "KnowledgeFile.filename"`)}
	}
	if v, ok := _c.mutation.Filename(); ok {
		if err := knowledgefile.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.filename": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileType(); !ok {
		return &ValidationError{Name: "file_type", err: errors.New(`ent: missing required field "KnowledgeFile.file_type"`)}
	}
	if v, ok := _c.mutation.FileType(); ok {
		if err := knowledgefile.FileTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_type", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.file_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileSize(); !ok {
		return &ValidationError{Name: "file_size", err: errors.New(`ent: missing required field "KnowledgeFile.file_size"`)}
	}
	if _, ok := _c.mutation.StoragePath(); !ok {
		return &ValidationError{Name: "storage_path", err: errors.New(`ent: missing required field "KnowledgeFile.storage_path"`)}
	}
	if v, ok := _c.mutation.StoragePath(); ok {
		if err := knowledgefile.StoragePathValidator(v); err != nil {
			return &ValidationError{Name: "storage_path", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.storage_path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ContentHash(); ok {
		if err := knowledgefile.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.content_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "KnowledgeFile.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := knowledgefile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "KnowledgeFile.status": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "KnowledgeFile.user"`)}
	}
	return nil
}

func (_c *KnowledgeFileCreate) sqlSave(ctx context.Context) (*KnowledgeFile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *KnowledgeFileCreate) createSpec() (*KnowledgeFile, *sqlgraph.CreateSpec) {
	var (
		_node = &KnowledgeFile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(knowledgefile.Table, sqlgraph.NewFieldSpec(knowledgefile.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(knowledgefile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(knowledgefile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(knowledgefile.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Filename(); ok {
		_spec.SetField(knowledgefile.FieldFilename, field.TypeString, value)
		_node.Filename = value
	}
	if value, ok := _c.mutation.FileType(); ok {
		_spec.SetField(knowledgefile.FieldFileType, field.TypeString, value)
		_node.FileType = value
	}
	if value, ok := _c.mutation.FileSize(); ok {
		_spec.SetField(knowledgefile.FieldFileSize, field.TypeInt64, value)
		_node.FileSize = value
	}
	if value, ok := _c.mutation.StoragePath(); ok {
		_spec.SetField(knowledgefile.FieldStoragePath, field.TypeString, value)
		_node.StoragePath = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(knowledgefile.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(knowledgefile.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(knowledgefile.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(knowledgefile.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefile.UserTable,
			Columns: []string{knowledgefile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   knowledgefile.WorkspaceTable,
			Columns: []string{knowledgefile.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.KnowledgeFile.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KnowledgeFileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *KnowledgeFileCreate) OnConflict(opts ...sql.ConflictOption) *KnowledgeFileUpsertOne {
	_c.conflict = opts
	return &KnowledgeFileUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.KnowledgeFile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KnowledgeFileCreate) OnConflictColumns(columns ...string) *KnowledgeFileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KnowledgeFileUpsertOne{
		create: _c,
	}
}

type (
	// KnowledgeFileUpsertOne is the builder for "upsert"-ing
	//  one KnowledgeFile node.
	KnowledgeFileUpsertOne struct {
		create *KnowledgeFileCreate
	}

	// KnowledgeFileUpsert is the "OnConflict" setter.
	KnowledgeFileUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *KnowledgeFileUpsert) SetUpdatedAt(v time.Time) *KnowledgeFileUpsert {
	u.Set(knowledgefile.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *KnowledgeFileUpsert) UpdateUpdatedAt() *KnowledgeFileUpsert {
	u.SetExcluded(knowledgefile.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *KnowledgeFileUpsert) SetDeletedAt(v time.Time) *KnowledgeFileUpsert {
	u.Set(knowledgefile.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *KnowledgeFileUpsert) UpdateDeletedAt() *KnowledgeFileUpsert {
	u.SetExcluded(knowledgefile.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *KnowledgeFileUpsert) ClearDeletedAt() *KnowledgeFileUpsert {
	u.SetNull(knowledgefile.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *KnowledgeFileUpsert) SetUserID(v int64) *KnowledgeFileUpsert {
	u.Set(knowledgefile.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *KnowledgeFileUpsert) UpdateUserID() *KnowledgeFileUpsert {
	u.SetExcluded(knowledgefile.FieldUserID)
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *KnowledgeFileUpsert) SetWorkspaceID(v int64) *KnowledgeFileUpsert {
	u.Set(knowledgefile.FieldWorkspaceID, v)
	return u
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *KnowledgeFileUpsert) UpdateWorkspaceID() *KnowledgeFileUpsert {
	u.SetExcluded(knowledgefile.FieldWorkspaceID)
	return u
}

// ClearWorkspaceID clears the value of the "workspace_id" field.
func (u *KnowledgeFileUpsert) ClearWorkspaceID() *KnowledgeFileUpsert {
	u.SetNull(knowledgefile.FieldWorkspaceID)
	return u
}

// SetFilename sets the "filename" field.
func (u *KnowledgeFileUpsert) SetFilename(v string) *KnowledgeFileUpsert {
	u.Set(knowledgefile.FieldFilename, v)
	return u
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *KnowledgeFileUpsert) UpdateFilename() *KnowledgeFileUpsert {
	u.SetExcluded(knowledgefile.FieldFilename)
	return u
}

// SetFileType sets the "file_type" field.
func (u *KnowledgeFileUpsert) SetFileType(v string) *KnowledgeFileUpsert {
	u.Set(knowledgefile.FieldFileType, v)
	return u
}

// UpdateFileType sets the "file_type" field to the value that was provided on create.
func (u *KnowledgeFileUpsert) UpdateFileType() *KnowledgeFileUpsert {
	u.SetExcluded(knowledgefile.FieldFileType)
	return u
}

// SetFileSize sets the "file_size" field.
func (u *KnowledgeFileUpsert) SetFileSize(v int64) *KnowledgeFileUpsert {
	u.Set(knowledgefile.FieldFileSize, v)
	return u
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *KnowledgeFileUpsert) UpdateFileSize() *KnowledgeFileUpsert {
	u.SetExcluded(knowledgefile.FieldFileSize)
	return u
}

// AddFileSize adds v to the "file_size" field.
func (u *KnowledgeFileUpsert) AddFileSize(v int64) *KnowledgeFileUpsert {
	u.Add(knowledgefile.FieldFileSize, v)
	return u
}

// SetStoragePath sets the "storage_path" field.
func (u *KnowledgeFileUpsert) SetStoragePath(v string) *KnowledgeFileUpsert {
	u.Set(knowledgefile.FieldStoragePath, v)
	return u
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *KnowledgeFileUpsert) UpdateStoragePath() *KnowledgeFileUpsert {
	u.SetExcluded(knowledgefile.FieldStoragePath)
	return u
}

// SetContent sets the "content" field.
func (u *KnowledgeFileUpsert) SetContent(v string) *KnowledgeFileUpsert {
	u.Set(knowledgefile.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *KnowledgeFileUpsert) UpdateContent() *KnowledgeFileUpsert {
	u.SetExcluded(knowledgefile.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *KnowledgeFileUpsert) ClearContent() *KnowledgeFileUpsert {
	u.SetNull(knowledgefile.FieldContent)
	return u
}

// SetContentHash sets the "content_hash" field.
func (u *KnowledgeFileUpsert) SetContentHash(v string) *KnowledgeFileUpsert {
	u.Set(knowledgefile.FieldContentHash, v)
	return u
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *KnowledgeFileUpsert) UpdateContentHash() *KnowledgeFileUpsert {
	u.SetExcluded(knowledgefile.FieldContentHash)
	return u
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *KnowledgeFileUpsert) ClearContentHash() *KnowledgeFileUpsert {
	u.SetNull(knowledgefile.FieldContentHash)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *KnowledgeFileUpsert) SetMetadata(v map[string]interface{}) *KnowledgeFileUpsert {
	u.Set(knowledgefile.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *KnowledgeFileUpsert) UpdateMetadata() *KnowledgeFileUpsert {
	u.SetExcluded(knowledgefile.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *KnowledgeFileUpsert) ClearMetadata() *KnowledgeFileUpsert {
	u.SetNull(knowledgefile.FieldMetadata)
	return u
}

// SetStatus sets the "status" field.
func (u *KnowledgeFileUpsert) SetStatus(v string) *KnowledgeFileUpsert {
	u.Set(knowledgefile.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *KnowledgeFileUpsert) UpdateStatus() *KnowledgeFileUpsert {
	u.SetExcluded(knowledgefile.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.KnowledgeFile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *KnowledgeFileUpsertOne) UpdateNewValues() *KnowledgeFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(knowledgefile.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.KnowledgeFile.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *KnowledgeFileUpsertOne) Ignore() *KnowledgeFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KnowledgeFileUpsertOne) DoNothing() *KnowledgeFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KnowledgeFileCreate.OnConflict
// documentation for more info.
func (u *KnowledgeFileUpsertOne) Update(set func(*KnowledgeFileUpsert)) *KnowledgeFileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KnowledgeFileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *KnowledgeFileUpsertOne) SetUpdatedAt(v time.Time) *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *KnowledgeFileUpsertOne) UpdateUpdatedAt() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *KnowledgeFileUpsertOne) SetDeletedAt(v time.Time) *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *KnowledgeFileUpsertOne) UpdateDeletedAt() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *KnowledgeFileUpsertOne) ClearDeletedAt() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *KnowledgeFileUpsertOne) SetUserID(v int64) *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *KnowledgeFileUpsertOne) UpdateUserID() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateUserID()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *KnowledgeFileUpsertOne) SetWorkspaceID(v int64) *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *KnowledgeFileUpsertOne) UpdateWorkspaceID() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateWorkspaceID()
	})
}

// ClearWorkspaceID clears the value of the "workspace_id" field.
func (u *KnowledgeFileUpsertOne) ClearWorkspaceID() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.ClearWorkspaceID()
	})
}

// SetFilename sets the "filename" field.
func (u *KnowledgeFileUpsertOne) SetFilename(v string) *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetFilename(v)
	})
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *KnowledgeFileUpsertOne) UpdateFilename() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateFilename()
	})
}

// SetFileType sets the "file_type" field.
func (u *KnowledgeFileUpsertOne) SetFileType(v string) *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetFileType(v)
	})
}

// UpdateFileType sets the "file_type" field to the value that was provided on create.
func (u *KnowledgeFileUpsertOne) UpdateFileType() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateFileType()
	})
}

// SetFileSize sets the "file_size" field.
func (u *KnowledgeFileUpsertOne) SetFileSize(v int64) *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *KnowledgeFileUpsertOne) AddFileSize(v int64) *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *KnowledgeFileUpsertOne) UpdateFileSize() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateFileSize()
	})
}

// SetStoragePath sets the "storage_path" field.
func (u *KnowledgeFileUpsertOne) SetStoragePath(v string) *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetStoragePath(v)
	})
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *KnowledgeFileUpsertOne) UpdateStoragePath() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateStoragePath()
	})
}

// SetContent sets the "content" field.
func (u *KnowledgeFileUpsertOne) SetContent(v string) *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *KnowledgeFileUpsertOne) UpdateContent() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *KnowledgeFileUpsertOne) ClearContent() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.ClearContent()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *KnowledgeFileUpsertOne) SetContentHash(v string) *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *KnowledgeFileUpsertOne) UpdateContentHash() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateContentHash()
	})
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *KnowledgeFileUpsertOne) ClearContentHash() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.ClearContentHash()
	})
}

// SetMetadata sets the "metadata" field.
func (u *KnowledgeFileUpsertOne) SetMetadata(v map[string]interface{}) *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *KnowledgeFileUpsertOne) UpdateMetadata() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *KnowledgeFileUpsertOne) ClearMetadata() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.ClearMetadata()
	})
}

// SetStatus sets the "status" field.
func (u *KnowledgeFileUpsertOne) SetStatus(v string) *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *KnowledgeFileUpsertOne) UpdateStatus() *KnowledgeFileUpsertOne {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *KnowledgeFileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KnowledgeFileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KnowledgeFileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *KnowledgeFileUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *KnowledgeFileUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// KnowledgeFileCreateBulk is the builder for creating many KnowledgeFile entities in bulk.
type KnowledgeFileCreateBulk struct {
	config
	err      error
	builders []*KnowledgeFileCreate
	conflict []sql.ConflictOption
}

// Save creates the KnowledgeFile entities in the database.
func (_c *KnowledgeFileCreateBulk) Save(ctx context.Context) ([]*KnowledgeFile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*KnowledgeFile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*KnowledgeFileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *KnowledgeFileCreateBulk) SaveX(ctx context.Context) []*KnowledgeFile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *KnowledgeFileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *KnowledgeFileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.KnowledgeFile.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.KnowledgeFileUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *KnowledgeFileCreateBulk) OnConflict(opts ...sql.ConflictOption) *KnowledgeFileUpsertBulk {
	_c.conflict = opts
	return &KnowledgeFileUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.KnowledgeFile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *KnowledgeFileCreateBulk) OnConflictColumns(columns ...string) *KnowledgeFileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &KnowledgeFileUpsertBulk{
		create: _c,
	}
}

// KnowledgeFileUpsertBulk is the builder for "upsert"-ing
// a bulk of KnowledgeFile nodes.
type KnowledgeFileUpsertBulk struct {
	create *KnowledgeFileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.KnowledgeFile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *KnowledgeFileUpsertBulk) UpdateNewValues() *KnowledgeFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(knowledgefile.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.KnowledgeFile.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *KnowledgeFileUpsertBulk) Ignore() *KnowledgeFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *KnowledgeFileUpsertBulk) DoNothing() *KnowledgeFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the KnowledgeFileCreateBulk.OnConflict
// documentation for more info.
func (u *KnowledgeFileUpsertBulk) Update(set func(*KnowledgeFileUpsert)) *KnowledgeFileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&KnowledgeFileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *KnowledgeFileUpsertBulk) SetUpdatedAt(v time.Time) *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *KnowledgeFileUpsertBulk) UpdateUpdatedAt() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *KnowledgeFileUpsertBulk) SetDeletedAt(v time.Time) *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *KnowledgeFileUpsertBulk) UpdateDeletedAt() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *KnowledgeFileUpsertBulk) ClearDeletedAt() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *KnowledgeFileUpsertBulk) SetUserID(v int64) *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *KnowledgeFileUpsertBulk) UpdateUserID() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateUserID()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *KnowledgeFileUpsertBulk) SetWorkspaceID(v int64) *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *KnowledgeFileUpsertBulk) UpdateWorkspaceID() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateWorkspaceID()
	})
}

// ClearWorkspaceID clears the value of the "workspace_id" field.
func (u *KnowledgeFileUpsertBulk) ClearWorkspaceID() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.ClearWorkspaceID()
	})
}

// SetFilename sets the "filename" field.
func (u *KnowledgeFileUpsertBulk) SetFilename(v string) *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetFilename(v)
	})
}

// UpdateFilename sets the "filename" field to the value that was provided on create.
func (u *KnowledgeFileUpsertBulk) UpdateFilename() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateFilename()
	})
}

// SetFileType sets the "file_type" field.
func (u *KnowledgeFileUpsertBulk) SetFileType(v string) *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetFileType(v)
	})
}

// UpdateFileType sets the "file_type" field to the value that was provided on create.
func (u *KnowledgeFileUpsertBulk) UpdateFileType() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateFileType()
	})
}

// SetFileSize sets the "file_size" field.
func (u *KnowledgeFileUpsertBulk) SetFileSize(v int64) *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetFileSize(v)
	})
}

// AddFileSize adds v to the "file_size" field.
func (u *KnowledgeFileUpsertBulk) AddFileSize(v int64) *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.AddFileSize(v)
	})
}

// UpdateFileSize sets the "file_size" field to the value that was provided on create.
func (u *KnowledgeFileUpsertBulk) UpdateFileSize() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateFileSize()
	})
}

// SetStoragePath sets the "storage_path" field.
func (u *KnowledgeFileUpsertBulk) SetStoragePath(v string) *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetStoragePath(v)
	})
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *KnowledgeFileUpsertBulk) UpdateStoragePath() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateStoragePath()
	})
}

// SetContent sets the "content" field.
func (u *KnowledgeFileUpsertBulk) SetContent(v string) *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *KnowledgeFileUpsertBulk) UpdateContent() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *KnowledgeFileUpsertBulk) ClearContent() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.ClearContent()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *KnowledgeFileUpsertBulk) SetContentHash(v string) *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *KnowledgeFileUpsertBulk) UpdateContentHash() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateContentHash()
	})
}

// ClearContentHash clears the value of the "content_hash" field.
func (u *KnowledgeFileUpsertBulk) ClearContentHash() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.ClearContentHash()
	})
}

// SetMetadata sets the "metadata" field.
func (u *KnowledgeFileUpsertBulk) SetMetadata(v map[string]interface{}) *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *KnowledgeFileUpsertBulk) UpdateMetadata() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *KnowledgeFileUpsertBulk) ClearMetadata() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.ClearMetadata()
	})
}

// SetStatus sets the "status" field.
func (u *KnowledgeFileUpsertBulk) SetStatus(v string) *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *KnowledgeFileUpsertBulk) UpdateStatus() *KnowledgeFileUpsertBulk {
	return u.Update(func(s *KnowledgeFileUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *KnowledgeFileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the KnowledgeFileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for KnowledgeFileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *KnowledgeFileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
