// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/knowledgefile"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/workspace"
)

// KnowledgeFile is the model entity for the KnowledgeFile schema.
type KnowledgeFile struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 所属用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// 所属工作空间 ID
	WorkspaceID *int64 `json:"workspace_id,omitempty"`
	// 原始文件名
	Filename string `json:"filename,omitempty"`
	// 文件类型：pdf/txt/doc/csv 等
	FileType string `json:"file_type,omitempty"`
	// 文件大小（字节）
	FileSize int64 `json:"file_size,omitempty"`
	// 存储路径或 key
	StoragePath string `json:"storage_path,omitempty"`
	// 提取的文本内容
	Content string `json:"content,omitempty"`
	// 内容哈希（用于去重）
	ContentHash string `json:"content_hash,omitempty"`
	// 元数据：作者、标题、摘要等
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// 状态：uploaded/processing/ready/failed
	Status string `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the KnowledgeFileQuery when eager-loading is set.
	Edges        KnowledgeFileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// KnowledgeFileEdges holds the relations/edges for other nodes in the graph.
type KnowledgeFileEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Workspace holds the value of the workspace edge.
	Workspace *Workspace `json:"workspace,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e KnowledgeFileEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// WorkspaceOrErr returns the Workspace value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e KnowledgeFileEdges) WorkspaceOrErr() (*Workspace, error) {
	if e.Workspace != nil {
		return e.Workspace, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: workspace.Label}
	}
	return nil, &NotLoadedError{edge: "workspace"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KnowledgeFile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case knowledgefile.FieldMetadata:
			values[i] = new([]byte)
		case knowledgefile.FieldID, knowledgefile.FieldUserID, knowledgefile.FieldWorkspaceID, knowledgefile.FieldFileSize:
			values[i] = new(sql.NullInt64)
		case knowledgefile.FieldFilename, knowledgefile.FieldFileType, knowledgefile.FieldStoragePath, knowledgefile.FieldContent, knowledgefile.FieldContentHash, knowledgefile.FieldStatus:
			values[i] = new(sql.NullString)
		case knowledgefile.FieldCreatedAt, knowledgefile.FieldUpdatedAt, knowledgefile.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KnowledgeFile fields.
func (_m *KnowledgeFile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case knowledgefile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case knowledgefile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case knowledgefile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case knowledgefile.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case knowledgefile.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case knowledgefile.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				_m.WorkspaceID = new(int64)
				*_m.WorkspaceID = value.Int64
			}
		case knowledgefile.FieldFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field filename", values[i])
			} else if value.Valid {
				_m.Filename = value.String
			}
		case knowledgefile.FieldFileType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_type", values[i])
			} else if value.Valid {
				_m.FileType = value.String
			}
		case knowledgefile.FieldFileSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[i])
			} else if value.Valid {
				_m.FileSize = value.Int64
			}
		case knowledgefile.FieldStoragePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_path", values[i])
			} else if value.Valid {
				_m.StoragePath = value.String
			}
		case knowledgefile.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case knowledgefile.FieldContentHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_hash", values[i])
			} else if value.Valid {
				_m.ContentHash = value.String
			}
		case knowledgefile.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case knowledgefile.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KnowledgeFile.
// This includes values selected through modifiers, order, etc.
func (_m *KnowledgeFile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the KnowledgeFile entity.
func (_m *KnowledgeFile) QueryUser() *UserQuery {
	return NewKnowledgeFileClient(_m.config).QueryUser(_m)
}

// QueryWorkspace queries the "workspace" edge of the KnowledgeFile entity.
func (_m *KnowledgeFile) QueryWorkspace() *WorkspaceQuery {
	return NewKnowledgeFileClient(_m.config).QueryWorkspace(_m)
}

// Update returns a builder for updating this KnowledgeFile.
// Note that you need to call KnowledgeFile.Unwrap() before calling this method if this KnowledgeFile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *KnowledgeFile) Update() *KnowledgeFileUpdateOne {
	return NewKnowledgeFileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the KnowledgeFile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *KnowledgeFile) Unwrap() *KnowledgeFile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: KnowledgeFile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *KnowledgeFile) String() string {
	var builder strings.Builder
	builder.WriteString("KnowledgeFile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.WorkspaceID; v != nil {
		builder.WriteString("workspace_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("filename=")
	builder.WriteString(_m.Filename)
	builder.WriteString(", ")
	builder.WriteString("file_type=")
	builder.WriteString(_m.FileType)
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(fmt.Sprintf("%v", _m.FileSize))
	builder.WriteString(", ")
	builder.WriteString("storage_path=")
	builder.WriteString(_m.StoragePath)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("content_hash=")
	builder.WriteString(_m.ContentHash)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// KnowledgeFiles is a parsable slice of KnowledgeFile.
type KnowledgeFiles []*KnowledgeFile
