// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/message"
)

// MessageCreate is the builder for creating a Message entity.
type MessageCreate struct {
	config
	mutation *MessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MessageCreate) SetCreatedAt(v time.Time) *MessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MessageCreate) SetNillableCreatedAt(v *time.Time) *MessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MessageCreate) SetUpdatedAt(v time.Time) *MessageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MessageCreate) SetNillableUpdatedAt(v *time.Time) *MessageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetConversationID sets the "conversation_id" field.
func (_c *MessageCreate) SetConversationID(v int64) *MessageCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *MessageCreate) SetRole(v string) *MessageCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *MessageCreate) SetContent(v string) *MessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetAttachments sets the "attachments" field.
func (_c *MessageCreate) SetAttachments(v []map[string]interface{}) *MessageCreate {
	_c.mutation.SetAttachments(v)
	return _c
}

// SetTokensUsed sets the "tokens_used" field.
func (_c *MessageCreate) SetTokensUsed(v int) *MessageCreate {
	_c.mutation.SetTokensUsed(v)
	return _c
}

// SetNillableTokensUsed sets the "tokens_used" field if the given value is not nil.
func (_c *MessageCreate) SetNillableTokensUsed(v *int) *MessageCreate {
	if v != nil {
		_c.SetTokensUsed(*v)
	}
	return _c
}

// SetCost sets the "cost" field.
func (_c *MessageCreate) SetCost(v float64) *MessageCreate {
	_c.mutation.SetCost(v)
	return _c
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_c *MessageCreate) SetNillableCost(v *float64) *MessageCreate {
	if v != nil {
		_c.SetCost(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *MessageCreate) SetModel(v string) *MessageCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *MessageCreate) SetNillableModel(v *string) *MessageCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *MessageCreate) SetMetadata(v map[string]interface{}) *MessageCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_c *MessageCreate) SetConversation(v *Conversation) *MessageCreate {
	return _c.SetConversationID(v.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (_c *MessageCreate) Mutation() *MessageMutation {
	return _c.mutation
}

// Save creates the Message in the database.
func (_c *MessageCreate) Save(ctx context.Context) (*Message, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MessageCreate) SaveX(ctx context.Context) *Message {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MessageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := message.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := message.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TokensUsed(); !ok {
		v := message.DefaultTokensUsed
		_c.mutation.SetTokensUsed(v)
	}
	if _, ok := _c.mutation.Cost(); !ok {
		v := message.DefaultCost
		_c.mutation.SetCost(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MessageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Message.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Message.updated_at"`)}
	}
	if _, ok := _c.mutation.ConversationID(); !ok {
		return &ValidationError{Name: "conversation_id", err: errors.New(`ent: missing required field "Message.conversation_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "Message.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Message.content"`)}
	}
	if _, ok := _c.mutation.TokensUsed(); !ok {
		return &ValidationError{Name: "tokens_used", err: errors.New(`ent: missing required field "Message.tokens_used"`)}
	}
	if _, ok := _c.mutation.Cost(); !ok {
		return &ValidationError{Name: "cost", err: errors.New(`ent: missing required field "Message.cost"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := message.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "Message.model": %w`, err)}
		}
	}
	if len(_c.mutation.ConversationIDs()) == 0 {
		return &ValidationError{Name: "conversation", err: errors.New(`ent: missing required edge "Message.conversation"`)}
	}
	return nil
}

func (_c *MessageCreate) sqlSave(ctx context.Context) (*Message, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MessageCreate) createSpec() (*Message, *sqlgraph.CreateSpec) {
	var (
		_node = &Message{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(message.Table, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Attachments(); ok {
		_spec.SetField(message.FieldAttachments, field.TypeJSON, value)
		_node.Attachments = value
	}
	if value, ok := _c.mutation.TokensUsed(); ok {
		_spec.SetField(message.FieldTokensUsed, field.TypeInt, value)
		_node.TokensUsed = value
	}
	if value, ok := _c.mutation.Cost(); ok {
		_spec.SetField(message.FieldCost, field.TypeFloat64, value)
		_node.Cost = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(message.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(message.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ConversationTable,
			Columns: []string{message.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConversationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Message.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MessageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MessageCreate) OnConflict(opts ...sql.ConflictOption) *MessageUpsertOne {
	_c.conflict = opts
	return &MessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MessageCreate) OnConflictColumns(columns ...string) *MessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MessageUpsertOne{
		create: _c,
	}
}

type (
	// MessageUpsertOne is the builder for "upsert"-ing
	//  one Message node.
	MessageUpsertOne struct {
		create *MessageCreate
	}

	// MessageUpsert is the "OnConflict" setter.
	MessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MessageUpsert) SetUpdatedAt(v time.Time) *MessageUpsert {
	u.Set(message.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MessageUpsert) UpdateUpdatedAt() *MessageUpsert {
	u.SetExcluded(message.FieldUpdatedAt)
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *MessageUpsert) SetConversationID(v int64) *MessageUpsert {
	u.Set(message.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *MessageUpsert) UpdateConversationID() *MessageUpsert {
	u.SetExcluded(message.FieldConversationID)
	return u
}

// SetRole sets the "role" field.
func (u *MessageUpsert) SetRole(v string) *MessageUpsert {
	u.Set(message.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *MessageUpsert) UpdateRole() *MessageUpsert {
	u.SetExcluded(message.FieldRole)
	return u
}

// SetContent sets the "content" field.
func (u *MessageUpsert) SetContent(v string) *MessageUpsert {
	u.Set(message.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *MessageUpsert) UpdateContent() *MessageUpsert {
	u.SetExcluded(message.FieldContent)
	return u
}

// SetAttachments sets the "attachments" field.
func (u *MessageUpsert) SetAttachments(v []map[string]interface{}) *MessageUpsert {
	u.Set(message.FieldAttachments, v)
	return u
}

// UpdateAttachments sets the "attachments" field to the value that was provided on create.
func (u *MessageUpsert) UpdateAttachments() *MessageUpsert {
	u.SetExcluded(message.FieldAttachments)
	return u
}

// ClearAttachments clears the value of the "attachments" field.
func (u *MessageUpsert) ClearAttachments() *MessageUpsert {
	u.SetNull(message.FieldAttachments)
	return u
}

// SetTokensUsed sets the "tokens_used" field.
func (u *MessageUpsert) SetTokensUsed(v int) *MessageUpsert {
	u.Set(message.FieldTokensUsed, v)
	return u
}

// UpdateTokensUsed sets the "tokens_used" field to the value that was provided on create.
func (u *MessageUpsert) UpdateTokensUsed() *MessageUpsert {
	u.SetExcluded(message.FieldTokensUsed)
	return u
}

// AddTokensUsed adds v to the "tokens_used" field.
func (u *MessageUpsert) AddTokensUsed(v int) *MessageUpsert {
	u.Add(message.FieldTokensUsed, v)
	return u
}

// SetCost sets the "cost" field.
func (u *MessageUpsert) SetCost(v float64) *MessageUpsert {
	u.Set(message.FieldCost, v)
	return u
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *MessageUpsert) UpdateCost() *MessageUpsert {
	u.SetExcluded(message.FieldCost)
	return u
}

// AddCost adds v to the "cost" field.
func (u *MessageUpsert) AddCost(v float64) *MessageUpsert {
	u.Add(message.FieldCost, v)
	return u
}

// SetModel sets the "model" field.
func (u *MessageUpsert) SetModel(v string) *MessageUpsert {
	u.Set(message.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *MessageUpsert) UpdateModel() *MessageUpsert {
	u.SetExcluded(message.FieldModel)
	return u
}

// ClearModel clears the value of the "model" field.
func (u *MessageUpsert) ClearModel() *MessageUpsert {
	u.SetNull(message.FieldModel)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *MessageUpsert) SetMetadata(v map[string]interface{}) *MessageUpsert {
	u.Set(message.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *MessageUpsert) UpdateMetadata() *MessageUpsert {
	u.SetExcluded(message.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *MessageUpsert) ClearMetadata() *MessageUpsert {
	u.SetNull(message.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MessageUpsertOne) UpdateNewValues() *MessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(message.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Message.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MessageUpsertOne) Ignore() *MessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MessageUpsertOne) DoNothing() *MessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MessageCreate.OnConflict
// documentation for more info.
func (u *MessageUpsertOne) Update(set func(*MessageUpsert)) *MessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MessageUpsertOne) SetUpdatedAt(v time.Time) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateUpdatedAt() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *MessageUpsertOne) SetConversationID(v int64) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateConversationID() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetRole sets the "role" field.
func (u *MessageUpsertOne) SetRole(v string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateRole() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateRole()
	})
}

// SetContent sets the "content" field.
func (u *MessageUpsertOne) SetContent(v string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateContent() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateContent()
	})
}

// SetAttachments sets the "attachments" field.
func (u *MessageUpsertOne) SetAttachments(v []map[string]interface{}) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetAttachments(v)
	})
}

// UpdateAttachments sets the "attachments" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateAttachments() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateAttachments()
	})
}

// ClearAttachments clears the value of the "attachments" field.
func (u *MessageUpsertOne) ClearAttachments() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.ClearAttachments()
	})
}

// SetTokensUsed sets the "tokens_used" field.
func (u *MessageUpsertOne) SetTokensUsed(v int) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetTokensUsed(v)
	})
}

// AddTokensUsed adds v to the "tokens_used" field.
func (u *MessageUpsertOne) AddTokensUsed(v int) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.AddTokensUsed(v)
	})
}

// UpdateTokensUsed sets the "tokens_used" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateTokensUsed() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateTokensUsed()
	})
}

// SetCost sets the "cost" field.
func (u *MessageUpsertOne) SetCost(v float64) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *MessageUpsertOne) AddCost(v float64) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateCost() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateCost()
	})
}

// SetModel sets the "model" field.
func (u *MessageUpsertOne) SetModel(v string) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateModel() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *MessageUpsertOne) ClearModel() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.ClearModel()
	})
}

// SetMetadata sets the "metadata" field.
func (u *MessageUpsertOne) SetMetadata(v map[string]interface{}) *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *MessageUpsertOne) UpdateMetadata() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *MessageUpsertOne) ClearMetadata() *MessageUpsertOne {
	return u.Update(func(s *MessageUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *MessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MessageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MessageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MessageCreateBulk is the builder for creating many Message entities in bulk.
type MessageCreateBulk struct {
	config
	err      error
	builders []*MessageCreate
	conflict []sql.ConflictOption
}

// Save creates the Message entities in the database.
func (_c *MessageCreateBulk) Save(ctx context.Context) ([]*Message, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Message, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MessageCreateBulk) SaveX(ctx context.Context) []*Message {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Message.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MessageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *MessageUpsertBulk {
	_c.conflict = opts
	return &MessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MessageCreateBulk) OnConflictColumns(columns ...string) *MessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MessageUpsertBulk{
		create: _c,
	}
}

// MessageUpsertBulk is the builder for "upsert"-ing
// a bulk of Message nodes.
type MessageUpsertBulk struct {
	create *MessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MessageUpsertBulk) UpdateNewValues() *MessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(message.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Message.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MessageUpsertBulk) Ignore() *MessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MessageUpsertBulk) DoNothing() *MessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MessageCreateBulk.OnConflict
// documentation for more info.
func (u *MessageUpsertBulk) Update(set func(*MessageUpsert)) *MessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MessageUpsertBulk) SetUpdatedAt(v time.Time) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateUpdatedAt() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *MessageUpsertBulk) SetConversationID(v int64) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateConversationID() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetRole sets the "role" field.
func (u *MessageUpsertBulk) SetRole(v string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateRole() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateRole()
	})
}

// SetContent sets the "content" field.
func (u *MessageUpsertBulk) SetContent(v string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateContent() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateContent()
	})
}

// SetAttachments sets the "attachments" field.
func (u *MessageUpsertBulk) SetAttachments(v []map[string]interface{}) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetAttachments(v)
	})
}

// UpdateAttachments sets the "attachments" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateAttachments() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateAttachments()
	})
}

// ClearAttachments clears the value of the "attachments" field.
func (u *MessageUpsertBulk) ClearAttachments() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.ClearAttachments()
	})
}

// SetTokensUsed sets the "tokens_used" field.
func (u *MessageUpsertBulk) SetTokensUsed(v int) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetTokensUsed(v)
	})
}

// AddTokensUsed adds v to the "tokens_used" field.
func (u *MessageUpsertBulk) AddTokensUsed(v int) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.AddTokensUsed(v)
	})
}

// UpdateTokensUsed sets the "tokens_used" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateTokensUsed() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateTokensUsed()
	})
}

// SetCost sets the "cost" field.
func (u *MessageUpsertBulk) SetCost(v float64) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetCost(v)
	})
}

// AddCost adds v to the "cost" field.
func (u *MessageUpsertBulk) AddCost(v float64) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.AddCost(v)
	})
}

// UpdateCost sets the "cost" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateCost() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateCost()
	})
}

// SetModel sets the "model" field.
func (u *MessageUpsertBulk) SetModel(v string) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateModel() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateModel()
	})
}

// ClearModel clears the value of the "model" field.
func (u *MessageUpsertBulk) ClearModel() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.ClearModel()
	})
}

// SetMetadata sets the "metadata" field.
func (u *MessageUpsertBulk) SetMetadata(v map[string]interface{}) *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *MessageUpsertBulk) UpdateMetadata() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *MessageUpsertBulk) ClearMetadata() *MessageUpsertBulk {
	return u.Update(func(s *MessageUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *MessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
