// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/conversation"
	"github.com/Wei-Shaw/sub2api/ent/message"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MessageUpdate) SetUpdatedAt(v time.Time) *MessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *MessageUpdate) SetConversationID(v int64) *MessageUpdate {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableConversationID(v *int64) *MessageUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *MessageUpdate) SetRole(v string) *MessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableRole(v *string) *MessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdate) SetContent(v string) *MessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableContent(v *string) *MessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetAttachments sets the "attachments" field.
func (_u *MessageUpdate) SetAttachments(v []map[string]interface{}) *MessageUpdate {
	_u.mutation.SetAttachments(v)
	return _u
}

// AppendAttachments appends value to the "attachments" field.
func (_u *MessageUpdate) AppendAttachments(v []map[string]interface{}) *MessageUpdate {
	_u.mutation.AppendAttachments(v)
	return _u
}

// ClearAttachments clears the value of the "attachments" field.
func (_u *MessageUpdate) ClearAttachments() *MessageUpdate {
	_u.mutation.ClearAttachments()
	return _u
}

// SetTokensUsed sets the "tokens_used" field.
func (_u *MessageUpdate) SetTokensUsed(v int) *MessageUpdate {
	_u.mutation.ResetTokensUsed()
	_u.mutation.SetTokensUsed(v)
	return _u
}

// SetNillableTokensUsed sets the "tokens_used" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableTokensUsed(v *int) *MessageUpdate {
	if v != nil {
		_u.SetTokensUsed(*v)
	}
	return _u
}

// AddTokensUsed adds value to the "tokens_used" field.
func (_u *MessageUpdate) AddTokensUsed(v int) *MessageUpdate {
	_u.mutation.AddTokensUsed(v)
	return _u
}

// SetCost sets the "cost" field.
func (_u *MessageUpdate) SetCost(v float64) *MessageUpdate {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableCost(v *float64) *MessageUpdate {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *MessageUpdate) AddCost(v float64) *MessageUpdate {
	_u.mutation.AddCost(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *MessageUpdate) SetModel(v string) *MessageUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *MessageUpdate) SetNillableModel(v *string) *MessageUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *MessageUpdate) ClearModel() *MessageUpdate {
	_u.mutation.ClearModel()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MessageUpdate) SetMetadata(v map[string]interface{}) *MessageUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MessageUpdate) ClearMetadata() *MessageUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_u *MessageUpdate) SetConversation(v *Conversation) *MessageUpdate {
	return _u.SetConversationID(v.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdate) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the Conversation entity.
func (_u *MessageUpdate) ClearConversation() *MessageUpdate {
	_u.mutation.ClearConversation()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := message.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := message.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "Message.model": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.conversation"`)
	}
	return nil
}

func (_u *MessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attachments(); ok {
		_spec.SetField(message.FieldAttachments, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAttachments(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldAttachments, value)
		})
	}
	if _u.mutation.AttachmentsCleared() {
		_spec.ClearField(message.FieldAttachments, field.TypeJSON)
	}
	if value, ok := _u.mutation.TokensUsed(); ok {
		_spec.SetField(message.FieldTokensUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokensUsed(); ok {
		_spec.AddField(message.FieldTokensUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(message.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(message.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(message.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(message.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(message.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(message.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ConversationTable,
			Columns: []string{message.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ConversationTable,
			Columns: []string{message.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MessageUpdateOne) SetUpdatedAt(v time.Time) *MessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *MessageUpdateOne) SetConversationID(v int64) *MessageUpdateOne {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableConversationID(v *int64) *MessageUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *MessageUpdateOne) SetRole(v string) *MessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableRole(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MessageUpdateOne) SetContent(v string) *MessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableContent(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetAttachments sets the "attachments" field.
func (_u *MessageUpdateOne) SetAttachments(v []map[string]interface{}) *MessageUpdateOne {
	_u.mutation.SetAttachments(v)
	return _u
}

// AppendAttachments appends value to the "attachments" field.
func (_u *MessageUpdateOne) AppendAttachments(v []map[string]interface{}) *MessageUpdateOne {
	_u.mutation.AppendAttachments(v)
	return _u
}

// ClearAttachments clears the value of the "attachments" field.
func (_u *MessageUpdateOne) ClearAttachments() *MessageUpdateOne {
	_u.mutation.ClearAttachments()
	return _u
}

// SetTokensUsed sets the "tokens_used" field.
func (_u *MessageUpdateOne) SetTokensUsed(v int) *MessageUpdateOne {
	_u.mutation.ResetTokensUsed()
	_u.mutation.SetTokensUsed(v)
	return _u
}

// SetNillableTokensUsed sets the "tokens_used" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableTokensUsed(v *int) *MessageUpdateOne {
	if v != nil {
		_u.SetTokensUsed(*v)
	}
	return _u
}

// AddTokensUsed adds value to the "tokens_used" field.
func (_u *MessageUpdateOne) AddTokensUsed(v int) *MessageUpdateOne {
	_u.mutation.AddTokensUsed(v)
	return _u
}

// SetCost sets the "cost" field.
func (_u *MessageUpdateOne) SetCost(v float64) *MessageUpdateOne {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableCost(v *float64) *MessageUpdateOne {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *MessageUpdateOne) AddCost(v float64) *MessageUpdateOne {
	_u.mutation.AddCost(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *MessageUpdateOne) SetModel(v string) *MessageUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *MessageUpdateOne) SetNillableModel(v *string) *MessageUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// ClearModel clears the value of the "model" field.
func (_u *MessageUpdateOne) ClearModel() *MessageUpdateOne {
	_u.mutation.ClearModel()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MessageUpdateOne) SetMetadata(v map[string]interface{}) *MessageUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MessageUpdateOne) ClearMetadata() *MessageUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_u *MessageUpdateOne) SetConversation(v *Conversation) *MessageUpdateOne {
	return _u.SetConversationID(v.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (_u *MessageUpdateOne) Mutation() *MessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the Conversation entity.
func (_u *MessageUpdateOne) ClearConversation() *MessageUpdateOne {
	_u.mutation.ClearConversation()
	return _u
}

// Where appends a list predicates to the MessageUpdate builder.
func (_u *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Message entity.
func (_u *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := message.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MessageUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := message.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Message.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := message.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "Message.model": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.conversation"`)
	}
	return nil
}

func (_u *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(message.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attachments(); ok {
		_spec.SetField(message.FieldAttachments, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAttachments(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldAttachments, value)
		})
	}
	if _u.mutation.AttachmentsCleared() {
		_spec.ClearField(message.FieldAttachments, field.TypeJSON)
	}
	if value, ok := _u.mutation.TokensUsed(); ok {
		_spec.SetField(message.FieldTokensUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokensUsed(); ok {
		_spec.AddField(message.FieldTokensUsed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(message.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(message.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(message.FieldModel, field.TypeString, value)
	}
	if _u.mutation.ModelCleared() {
		_spec.ClearField(message.FieldModel, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(message.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(message.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ConversationTable,
			Columns: []string{message.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ConversationTable,
			Columns: []string{message.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
